"""Data pipeline: portable manifests, dataset, transforms and reproducible splits.

Design notes (from the refactoring plan):
- The single source of truth is a **CSV manifest** with platform-independent relative
  paths (POSIX separators), replacing the old ``train.txt`` / ``valid.txt`` files.
- Manifests are generated by ``prepare-data`` with a fixed seed, stratified split,
  duplicate/bad-image validation and a checksum record.
"""

from __future__ import annotations

import csv
import hashlib
import random
from collections import Counter
from pathlib import Path

import yaml
from PIL import Image


class ManifestError(RuntimeError):
    """Raised when a manifest is missing, corrupt or inconsistent."""


def _relpath(path: Path, root: Path) -> str:
    """Return a POSIX relative path from ``root`` to ``path``."""
    return path.resolve().relative_to(root.resolve()).as_posix()


def _iter_images(data_dir: Path, extensions: tuple[str, ...] = (".jpg", ".jpeg", ".png")) -> list[tuple[str, Path]]:
    """Yield (class_name, image_path) for every image under ``data_dir``."""
    samples: list[tuple[str, Path]] = []
    if not data_dir.is_dir():
        raise FileNotFoundError(f"data dir not found: {data_dir}")
    for class_dir in sorted(p for p in data_dir.iterdir() if p.is_dir()):
        for img in sorted(p for p in class_dir.iterdir() if p.suffix.lower() in extensions):
            if img.name.startswith("._"):  # skip macOS AppleDouble junk
                continue
            samples.append((class_dir.name, img))
    return samples


def validate_image(path: Path) -> bool:
    """Return True if the file is a readable image."""
    try:
        with Image.open(path) as im:
            im.verify()
        return True
    except Exception:
        return False


def _checksum(text: str) -> str:
    return hashlib.sha256(text.encode()).hexdigest()[:16]


def find_duplicates(data_dir: str | Path, extensions: tuple[str, ...] = (".jpg", ".jpeg", ".png")) -> list[list[str]]:
    """Group image paths by content hash; return groups with more than one member.

    Learning note: file names can lie (same image copied under different names), so
    content hashing is the reliable way to detect duplicates before training.
    """
    import hashlib

    root = Path(data_dir).resolve()
    by_hash: dict[str, list[str]] = {}
    for class_dir in sorted(p for p in root.iterdir() if p.is_dir()):
        for img in sorted(p for p in class_dir.iterdir() if p.suffix.lower() in extensions):
            if img.name.startswith("._"):
                continue
            h = hashlib.sha256(img.read_bytes()).hexdigest()
            by_hash.setdefault(h, []).append(str(img))
    return [paths for paths in by_hash.values() if len(paths) > 1]


def build_manifest(
    data_dir: str | Path,
    manifest_dir: str | Path,
    split_ratios: list[float] = (0.8, 0.1, 0.1),
    seed: int = 666,
    validate: bool = True,
) -> dict[str, Path]:
    """Split ``data_dir`` (class folders) into train/valid/test CSV manifests.

    Returns a mapping split -> manifest path. Stratified per class, fixed seed.
    """
    root = Path(data_dir).resolve()
    out_dir = Path(manifest_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    samples = _iter_images(root)
    if not samples:
        raise ManifestError(f"no images found under {root}")

    classes = sorted({c for c, _ in samples})
    class_index = {c: i for i, c in enumerate(classes)}

    # stratified shuffle per class, then assign to splits by ratio
    per_class: dict[str, list[Path]] = {c: [] for c in classes}
    for cls, path in samples:
        per_class[cls].append(path)

    rng = random.Random(seed)
    for paths in per_class.values():
        rng.shuffle(paths)

    splits: dict[str, list[tuple[str, str]]] = {"train": [], "valid": [], "test": []}
    for cls, paths in per_class.items():
        n = len(paths)
        n_train = int(n * split_ratios[0])
        n_valid = int(n * (split_ratios[0] + split_ratios[1])) - n_train
        for i, p in enumerate(paths):
            if i < n_train:
                split = "train"
            elif i < n_train + n_valid:
                split = "valid"
            else:
                split = "test"
            splits[split].append((_relpath(p, root), str(class_index[cls])))

    bad: list[str] = []
    if validate:
        for _cls, paths in per_class.items():
            for p in paths:
                if not validate_image(p):
                    bad.append(str(p))
        if bad:
            raise ManifestError(f"{len(bad)} unreadable images, e.g. {bad[:3]}")

    manifest_paths: dict[str, Path] = {}
    for split, rows in splits.items():
        if not rows:
            continue
        path = out_dir / f"{split}.csv"
        with path.open("w", newline="") as f:
            writer = csv.writer(f)
            writer.writerow(["path", "label"])
            writer.writerows(rows)
        manifest_paths[split] = path

    # summary + checksum of the train manifest (audit record)
    summary_path = out_dir / "summary.txt"
    lines = [
        f"seed={seed}",
        f"split_ratios={list(split_ratios)}",
        f"classes={classes}",
        f"class_index={class_index}",
        f"train={len(splits['train'])} valid={len(splits['valid'])} test={len(splits['test'])}",
        f"per_class_train={dict(sorted(Counter(r[1] for r in splits['train']).items()))}",
    ]
    if "train" in manifest_paths:
        lines.append(f"train_manifest_sha256={_checksum(manifest_paths['train'].read_text())}")
    summary_path.write_text("\n".join(lines) + "\n")

    # record the data root + classes so manifests are self-describing
    (out_dir / "source.yaml").write_text(
        yaml.safe_dump({"data_dir": str(root), "classes": classes, "class_index": class_index})
    )
    return manifest_paths


def manifest_classes(manifest_dir: str | Path) -> list[str]:
    """Return the class list recorded when the manifests were built."""
    src = Path(manifest_dir) / "source.yaml"
    if not src.exists():
        raise ManifestError(f"missing {src}; regenerate manifests with prepare-data")
    classes = yaml.safe_load(src.read_text()).get("classes")
    if not classes:
        raise ManifestError(f"no class list recorded in {src}")
    return list(classes)


def manifest_root(manifest_dir: str | Path) -> Path:
    """Return the data root recorded when the manifests were built."""
    src = Path(manifest_dir) / "source.yaml"
    if not src.exists():
        raise ManifestError(f"missing {src}; regenerate manifests with prepare-data")
    return Path(yaml.safe_load(src.read_text())["data_dir"]).resolve()



def load_manifest(manifest_path: str | Path, root_dir: str | Path) -> list[tuple[str, int]]:
    """Load a manifest CSV into [(absolute_path, label)] with path validation."""
    root = Path(root_dir).resolve()
    p = Path(manifest_path)
    if not p.exists():
        raise ManifestError(f"manifest not found: {p}")
    rows: list[tuple[str, int]] = []
    with p.open() as f:
        reader = csv.DictReader(f)
        for row in reader:
            rel = row["path"]
            abs_path = (root / rel).resolve()
            if not abs_path.is_file():
                raise ManifestError(f"manifest entry missing on disk: {abs_path}")
            rows.append((str(abs_path), int(row["label"])))
    return rows
