"""Data pipeline: portable manifests, dataset, transforms and reproducible splits.

Design notes (from the refactoring plan):
- The single source of truth is a **CSV manifest** with platform-independent relative
  paths (POSIX separators), replacing the old ``train.txt`` / ``valid.txt`` files.
- Manifests are generated by ``prepare-data`` with a fixed seed, stratified split,
  duplicate/bad-image validation and a checksum record.
"""

from __future__ import annotations

import csv
import hashlib
import os
import random
from collections import Counter
from pathlib import Path

import yaml
from PIL import Image


class ManifestError(RuntimeError):
    """Raised when a manifest is missing, corrupt or inconsistent."""


def _relpath(path: Path, root: Path) -> str:
    """Return a POSIX relative path from ``root`` to ``path``."""
    return path.resolve().relative_to(root.resolve()).as_posix()


def _iter_images(data_dir: Path, extensions: tuple[str, ...] = (".jpg", ".jpeg", ".png")) -> list[tuple[str, Path]]:
    """Yield (class_name, image_path) for every image under ``data_dir``."""
    samples: list[tuple[str, Path]] = []
    if not data_dir.is_dir():
        raise FileNotFoundError(f"data dir not found: {data_dir}")
    for class_dir in sorted(p for p in data_dir.iterdir() if p.is_dir()):
        for img in sorted(p for p in class_dir.iterdir() if p.suffix.lower() in extensions):
            if img.name.startswith("._"):  # skip macOS AppleDouble junk
                continue
            samples.append((class_dir.name, img))
    return samples


def validate_image(path: Path) -> bool:
    """Return True if the file is a readable image."""
    try:
        with Image.open(path) as im:
            im.verify()
        return True
    except Exception:
        return False


def _checksum(text: str) -> str:
    return hashlib.sha256(text.encode()).hexdigest()[:16]


def _content_groups(samples: list[tuple[str, Path]]) -> dict[str, list[tuple[str, Path]]]:
    """Group samples by their full SHA-256 content hash."""
    groups: dict[str, list[tuple[str, Path]]] = {}
    for cls, path in samples:
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        groups.setdefault(digest, []).append((cls, path))
    return groups


def find_duplicates(data_dir: str | Path, extensions: tuple[str, ...] = (".jpg", ".jpeg", ".png")) -> list[list[str]]:
    """Group image paths by content hash; return groups with more than one member.

    Learning note: file names can lie (same image copied under different names), so
    content hashing is the reliable way to detect duplicates before training.
    """
    root = Path(data_dir).resolve()
    groups = _content_groups(_iter_images(root, extensions))
    return [[str(path) for _cls, path in group] for group in groups.values() if len(group) > 1]


def _describe_group(group: list[tuple[str, Path]], root: Path) -> str:
    return ", ".join(f"{_relpath(path, root)} (class {cls!r})" for cls, path in group)


def _split_groups(groups: list[list[Path]], split_ratios: list[float], rng: random.Random) -> dict[str, list[Path]]:
    """Assign indivisible content groups with minimum target-count deviation."""
    split_names = ("train", "valid", "test")
    shuffled = list(groups)
    rng.shuffle(shuffled)
    total = sum(len(group) for group in shuffled)
    targets = {
        "train": int(total * split_ratios[0]),
        "valid": int(total * (split_ratios[0] + split_ratios[1])) - int(total * split_ratios[0]),
    }
    targets["test"] = total - targets["train"] - targets["valid"]

    if all(len(group) == 1 for group in shuffled):
        n_train = targets["train"]
        n_valid = targets["valid"]
        return {
            "train": [path for group in shuffled[:n_train] for path in group],
            "valid": [path for group in shuffled[n_train : n_train + n_valid] for path in group],
            "test": [path for group in shuffled[n_train + n_valid :] for path in group],
        }

    duplicate_groups = sorted((group for group in shuffled if len(group) > 1), key=len, reverse=True)
    singleton_groups = [group for group in shuffled if len(group) == 1]

    # State is (train_count, valid_count) -> base-3 encoded split choices.
    # Test count is implied by the duplicate samples processed so far.
    states: dict[tuple[int, int], int] = {(0, 0): 0}
    for group in duplicate_groups:
        size = len(group)
        next_states: dict[tuple[int, int], int] = {}
        for (train_count, valid_count), choices in states.items():
            candidates = (
                (train_count + size, valid_count),
                (train_count, valid_count + size),
                (train_count, valid_count),
            )
            for split_index, state in enumerate(candidates):
                next_states.setdefault(state, choices * 3 + split_index)
        states = next_states

    duplicate_total = sum(len(group) for group in duplicate_groups)
    singleton_count = len(singleton_groups)

    def complete_counts(train_count: int, valid_count: int) -> tuple[int, int, int]:
        counts = [train_count, valid_count, duplicate_total - train_count - valid_count]
        remaining = singleton_count
        for index, split in enumerate(split_names):
            added = min(remaining, max(0, targets[split] - counts[index]))
            counts[index] += added
            remaining -= added
        counts[0] += remaining
        return counts[0], counts[1], counts[2]

    def final_score(state: tuple[int, int]) -> tuple[int, int, int, int, int]:
        counts = complete_counts(*state)
        deviations = tuple(abs(counts[index] - targets[split]) for index, split in enumerate(split_names))
        return (
            sum(deviations),
            sum(max(0, counts[index] - targets[split]) for index, split in enumerate(split_names)),
            *deviations,
        )

    best_state = min(states, key=final_score)
    final_counts = complete_counts(*best_state)
    encoded_choices = states[best_state]
    duplicate_choices = []
    for _group in reversed(duplicate_groups):
        duplicate_choices.append(encoded_choices % 3)
        encoded_choices //= 3
    duplicate_choices.reverse()

    assigned = {split: [] for split in split_names}
    for group, split_index in zip(duplicate_groups, duplicate_choices, strict=True):
        assigned[split_names[split_index]].extend(group)

    singleton_targets = [final_counts[index] - len(assigned[split]) for index, split in enumerate(split_names)]
    offset = 0
    for split, count in zip(split_names, singleton_targets, strict=True):
        selected = singleton_groups[offset : offset + count]
        assigned[split].extend(path for group in selected for path in group)
        offset += count
    return assigned


def _source_metadata(root: Path, out_dir: Path, classes: list[str], class_index: dict[str, int]) -> dict:
    """Build versioned, portable source metadata for a manifest set."""
    try:
        root_path = os.path.relpath(root, out_dir.resolve())
        data_root = {"path": Path(root_path).as_posix(), "relative_to": "manifest_dir"}
    except ValueError:
        data_root = {"path": str(root), "relative_to": None}
    return {
        "schema_version": 1,
        "data_root": data_root,
        "classes": classes,
        "class_index": class_index,
    }


def build_manifest(
    data_dir: str | Path,
    manifest_dir: str | Path,
    split_ratios: list[float] = (0.8, 0.1, 0.1),
    seed: int = 666,
    validate: bool = True,
    strict: bool = False,
) -> dict[str, Path]:
    """Split ``data_dir`` (class folders) into train/valid/test CSV manifests.

    Returns a mapping split -> manifest path. Stratified per class, fixed seed.
    """
    root = Path(data_dir).resolve()
    out_dir = Path(manifest_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    samples = _iter_images(root)
    if not samples:
        raise ManifestError(f"no images found under {root}")

    classes = sorted({c for c, _ in samples})
    class_index = {c: i for i, c in enumerate(classes)}  # 类别名 -> 数字标签（字母序）

    content_groups = _content_groups(samples)
    duplicate_groups = [group for group in content_groups.values() if len(group) > 1]
    for group in duplicate_groups:
        group_classes = {cls for cls, _path in group}
        if len(group_classes) > 1:
            raise ManifestError(
                "annotation conflict: identical image content has multiple classes: " + _describe_group(group, root)
            )
    if strict and duplicate_groups:
        raise ManifestError(
            "duplicate image content found in strict mode: " + _describe_group(duplicate_groups[0], root)
        )

    # ---- 分层切分（stratified split）----
    # 为什么不全局打乱再切？因为某个类别可能样本很少，全局打乱后可能全部挤进
    # 训练集。分层 = 对每个类别独立打乱，再按同一比例切，保证每个类别在
    # train/valid/test 中的比例一致。
    per_class: dict[str, list[list[Path]]] = {c: [] for c in classes}
    for group in content_groups.values():
        cls = group[0][0]
        per_class[cls].append([path for _group_cls, path in group])

    # 用独立 Random(seed) 实例而不是全局 random：只影响本次切分，不影响
    # 训练阶段其他随机性；固定 seed 保证任何人重跑得到完全相同的切分。
    rng = random.Random(seed)
    splits: dict[str, list[tuple[str, str]]] = {"train": [], "valid": [], "test": []}
    for cls, groups in per_class.items():
        for split, paths in _split_groups(groups, split_ratios, rng).items():
            for path in paths:
                # 存相对路径（跨平台可移植）+ 数字标签（训练时用整数，不用字符串）
                splits[split].append((_relpath(path, root), str(class_index[cls])))

    bad: list[str] = []
    if validate:
        # 坏图检测：train/valid/test 里混入坏图会导致训练中途崩溃，
        # 且崩的位置难以排查 —— 提前在数据准备阶段就拦下来。
        for _cls, path in samples:
            if not validate_image(path):
                bad.append(str(path))
        if bad:
            raise ManifestError(f"{len(bad)} unreadable images, e.g. {bad[:3]}")

    manifest_paths: dict[str, Path] = {}
    for split, rows in splits.items():
        if not rows:
            continue
        path = out_dir / f"{split}.csv"
        with path.open("w", newline="") as f:
            writer = csv.writer(f)
            writer.writerow(["path", "label"])
            writer.writerows(rows)
        manifest_paths[split] = path

    # summary + checksum of the train manifest (audit record)
    # 这份摘要就是"数据审计记录"：类别数、每类数量、切分比例、种子、校验和。
    # 任何人拿它可以核对"这份切分是不是标准的那份"，是实验可复现的第一环。
    summary_path = out_dir / "summary.txt"
    lines = [
        f"seed={seed}",
        f"split_ratios={list(split_ratios)}",
        f"classes={classes}",
        f"class_index={class_index}",
        f"train={len(splits['train'])} valid={len(splits['valid'])} test={len(splits['test'])}",
        f"per_class_train={dict(sorted(Counter(r[1] for r in splits['train']).items()))}",
    ]
    if "train" in manifest_paths:
        lines.append(f"train_manifest_sha256={_checksum(manifest_paths['train'].read_text())}")
    summary_path.write_text("\n".join(lines) + "\n")

    # record the data root + classes so manifests are self-describing
    (out_dir / "source.yaml").write_text(
        yaml.safe_dump(_source_metadata(root, out_dir, classes, class_index), sort_keys=False)
    )
    return manifest_paths


def manifest_classes(manifest_dir: str | Path) -> list[str]:
    """Return the class list recorded when the manifests were built."""
    src = Path(manifest_dir) / "source.yaml"
    if not src.exists():
        raise ManifestError(f"missing {src}; regenerate manifests with prepare-data")
    classes = yaml.safe_load(src.read_text()).get("classes")
    if not classes:
        raise ManifestError(f"no class list recorded in {src}")
    return list(classes)


def manifest_root(manifest_dir: str | Path) -> Path:
    """Return the data root recorded when the manifests were built."""
    manifest_path = Path(manifest_dir)
    src = manifest_path / "source.yaml"
    if not src.exists():
        raise ManifestError(f"missing {src}; regenerate manifests with prepare-data")
    source = yaml.safe_load(src.read_text()) or {}
    if "data_root" in source:
        data_root = source["data_root"]
        if not isinstance(data_root, dict) or "path" not in data_root:
            raise ManifestError(f"invalid data_root recorded in {src}")
        path = Path(data_root["path"])
        relative_to = data_root.get("relative_to")
        if relative_to == "manifest_dir":
            return (manifest_path / path).resolve()
        if relative_to is None and path.is_absolute():
            return path.resolve()
        raise ManifestError(f"unsupported data_root schema in {src}: relative_to={relative_to!r}")
    if "data_dir" in source:
        return Path(source["data_dir"]).resolve()
    raise ManifestError(f"no data root recorded in {src}")


def load_manifest(manifest_path: str | Path, root_dir: str | Path) -> list[tuple[str, int]]:
    """Load a manifest CSV into [(absolute_path, label)] with path validation."""
    root = Path(root_dir).resolve()
    p = Path(manifest_path)
    if not p.exists():
        raise ManifestError(f"manifest not found: {p}")
    rows: list[tuple[str, int]] = []
    with p.open() as f:
        reader = csv.DictReader(f)
        for row in reader:
            rel = row["path"]
            abs_path = (root / rel).resolve()
            try:
                abs_path.relative_to(root)
            except ValueError as exc:
                raise ManifestError(f"manifest entry outside data root: {rel!r}; root={root}") from exc
            if not abs_path.is_file():
                raise ManifestError(f"manifest entry missing on disk: {abs_path}")
            rows.append((str(abs_path), int(row["label"])))
    return rows
